Issue/#4
cawauchi6204/docker-laravel-handson pull request #13
Opened 2020-11-02 12:47 UTC by cawauchi6204

完成しましたのでお手隙の際にご確認いただければと思います

2020-11-04 10:24 UTC, wazyu-17 requested changes

2020-11-04 10:24 UTC, wazyu-17 commented on backend/app/Http/Controllers/PostsController.php
> +      'updated_at' => $now,
created_atとupdated_atは自動で入る値なので、なしでも良いと思います。

2020-11-04 10:24 UTC, wazyu-17 commented on backend/app/Http/Controllers/PostsController.php
> +    DB::table('posts')->insert($param);
laravelのModelを作りましょう！
作っておくとリレーションやデータ登録が楽になります
https://udemy.benesse.co.jp/development/web/laravel-model.html

2020-11-04 10:24 UTC, wazyu-17 commented on backend/routes/web.php
> +Route::post('/','App\Http\Controllers\PostsController@store');
パスではなくコントローラーを定義しましょう。
例
Route::get('user/profile', 'UserProfileController@show')->name('profile');
https://readouble.com/laravel/5.7/ja/routing.html

2020-11-04 12:53 UTC, cawauchi6204 commented on backend/app/Http/Controllers/PostsController.php
> +      'updated_at' => $now,
了解しました！

2020-11-05 10:29 UTC, cawauchi6204 commented on backend/routes/web.php
> +Route::post('/','App\Http\Controllers\PostsController@store');
<form action="{{ route('post') }}" method="POST">
とformで設定して第一引数をpostに変えてみて末尾に->('post')をつけてみる

2020-11-14 03:55 UTC, wazyu-17 reviewed
確認しました！

2020-11-14 03:55 UTC, wazyu-17 commented on backend/routes/web.php
> +Route::post('post', [PostsController::class,'store'])->name('post');
こちらのルーティングは、postではなく、storeで良いのでは？
シングルクォーテーションで囲まれているとことnameのとこですかね。

登録という処理なのでpostという名前はあってない気がしました。

2020-11-14 03:55 UTC, wazyu-17 commented on backend/app/Http/Controllers/PostsController.php
> +    return 'hoge';
こちらはテスト用のメソッドだと思いますが、消しておきましょう！

2020-11-18 10:47 UTC, wazyu-17 approved these changes
良いですね！レビュー通過です！

2020-11-18 10:57 UTC, merged