#14完了
cawauchi6204/docker-laravel-handson pull request #19
Opened 2020-11-21 14:29 UTC by cawauchi6204

2020-11-22 04:04 UTC, wazyu-17 commented on backend/app/Models/Comment.php
> +  {
すみません。このscopeGetCommentはどこで使用しているのでしょう？

2020-11-22 04:04 UTC, wazyu-17 commented on backend/resources/views/includes/comment_form.blade.php
> +      <input type="hidden" name="posts_id" value={{ $posts_data->id }} />
postをpostsにしている理由はなにかあるのでしょうか。
送信しているデータは複数系ではないと思いますが

2020-11-22 04:04 UTC, wazyu-17 commented on backend/app/Http/Controllers/PostsController.php
> +
下記ですがfirstでとれば、下の方で配列のindex指定せずに取得できますよ
参考：https://qiita.com/sola-msr/items/fac931c72e1c46ae5f0f

```
$posts_data = Post::findPost($id);
```

2020-11-22 04:13 UTC, wazyu-17 commented
レビューしました！

すみません、プルリクエストする場合、詳細は書きましょう。
基本的にissueに書いてあるのは仕様で、プルリクエストは、どのように実装したかを書く場所です。

たとえば、

タイトル
コメント登録処理を実装

詳細

対象issue
#14 

## 内容
- ルーティングを実装
- コメントの登録画面を実装
- 対象のidの記事データのみ取得できるようにモデルを実装

みたいな感じです。
プルリクエストは言わば、レビューお願いです。
レビュー者にどのように実装したかわかりやすく記載してあげるのが礼儀になります。

かわうちさんが自分がレビュー者だったらどのような情報があったら理解しやすいのか？
という視点を持ってあげると相手もわかりやすいと思います！

今後、きっとかわうちさんも先輩になりレビュー者になっていくと思うので
まずは良いプルリクエストをかけるようにしましょう！

どのようなプルリクエストが良いのか調べてみるのも良いと思います！

参考
https://texta.pixta.jp/entry/2017/12/05/123000

2020-11-22 04:15 UTC, wazyu-17 commented
あと、commitもまとめてcommitではなく、機能ごとにでcommitを分けるようにしましょう。
分けるとこのcommitはこの機能についてのコード追加や修正とわかりやすくなります。

例
コメント画面を実装
→　コメントにtemplateのコードのみcommit

2020-11-23 05:17 UTC, cawauchi6204 commented on backend/app/Http/Controllers/PostsController.php
> +    $id = preg_replace('/[^0-9]/','',$id);
こちらの$idなのですが
$requestから数字のみが欲しいのですが$requestには数字のみのものが入っていなく、近いものとしてpathに入っているものが`"post/6"`となっており、preg_replaceで文字列を取り除いているのですが、数字のみを取り出す方法などございましたらアドバイスいただきたいです。

2020-11-23 05:39 UTC, cawauchi6204 commented on backend/app/Http/Controllers/PostsController.php
> +    $id = preg_replace('/[^0-9]/','',$id);
https://technote.space/programming/laravel-get-url-parameter

```php
例えばコントローラであれば以下のようにすることで {test} の部分である更新対象のIDを取得できます。

public function update(Request $request, $id)
Laravelはサービスコンテナという強力なDI機能があり、 FormRequest を拡張して更新用にバリデーションを行う実装を持たせた UpdateRequest などを作成し以下のように使用することで、このメソッドが呼ばれるときに自動でインスタンスを作成し、バリデーションを実行してくれるようになります。

public function update(UpdateRequest $request, $id)
```

いけそうです！

2020-11-23 08:16 UTC, cawauchi6204 commented on backend/app/Models/Comment.php
> +  public function scopeGetComment ($query,$id)
scopeはlaravelの本を読んでそのまま使ってました！

getCommentByIdは関数名だけでわかるので使わせていただきます！

https://laraweb.net/knowledge/2548/

2020-11-23 08:33 UTC, cawauchi6204 commented on backend/app/Models/Comment.php
> +  {
こちらはPostsController.phpの

$comment = Comment::getComment($id);

部分で使っております。

役割としては遷移後のpost/{id}のidの部分とcommentテーブルのposts_idカラムを参照してリレーションがあるならばそのデータを返しています。

2020-11-28 07:07 UTC, cawauchi6204 commented
@wazyu-17 さん

お疲れ様です。

日にちがたってしまいましたがご指摘いただいたコードの修正が完了しましたのでお手隙の際にご確認いただければと思います。

よろしくお願いします。

2020-11-30 11:55 UTC, wazyu-17 requested changes

2020-11-30 11:55 UTC, wazyu-17 commented on backend/app/Http/Controllers/CommentsController.php
> +    $comment->posts_id = $posts_id;
上記のposts_idの変数に格納する意味はあるのでしょうか？
下記で良い気がします。
```
$comment->posts_id = $request->posts_id;
```

また、posts_idという複数系は合っていますか？

2020-11-30 11:55 UTC, wazyu-17 commented on backend/app/Http/Controllers/PostsController.php
> +    $post = new Post;
こちらも$post = new Post();
にしましょう！

2020-11-30 11:55 UTC, wazyu-17 commented on backend/app/Http/Controllers/PostsController.php
> +    return redirect()->route('post.detail',['id' => $id]);
こちらも変数に格納する意味はあるのでしょうか？

2020-11-30 11:55 UTC, wazyu-17 commented on backend/app/Http/Controllers/PostsController.php
> +    return redirect()->route('post.detail',['id' => $id]);
あと、スペースを空けましょう。
```
return redirect()->route('post.detail', ['id' => $id]);
```
エディタのformat設定などはしましたか？

2020-11-30 11:55 UTC, wazyu-17 commented on backend/app/Http/Controllers/PostsController.php
> +    $post = Post::where('id',$id)->first();
こちらも,のあとはスペースを空けましょう

2020-11-30 11:55 UTC, wazyu-17 commented on backend/resources/views/includes/comment_form.blade.php
> +      <input type="hidden" name="posts_id" value={{ $post->id }} />
こちらのnameはpost_idで良いと思います。複数系ではないと思うので

2020-11-30 11:55 UTC, wazyu-17 commented on backend/routes/web.php
> +Route::get('post/{id}',[PostsController::class,'detail'])->name('post.detail');
ルーティングにprefixを使ってまとめるとみやすくなります
https://qiita.com/ntm718/items/95eee03f5294d0c351b0

2020-11-30 11:56 UTC, wazyu-17 commented
エディタのformatなどを設定すると良いと思います。
綺麗に書くことを意識しないとくせになります。

2020-11-30 12:53 UTC, cawauchi6204 commented on backend/routes/web.php
> +Route::get('post/{id}',[PostsController::class,'detail'])->name('post.detail');
prefixめちゃめちゃ良さそうです

修正します！

2020-11-30 12:56 UTC, cawauchi6204 commented on backend/app/Http/Controllers/PostsController.php
> +    $post = new Post;
すみません

修正し終わったらgrep使って他に変更すべき箇所がないか探すようにします

2020-11-30 12:57 UTC, cawauchi6204 commented on backend/app/Http/Controllers/PostsController.php
> +    return redirect()->route('post.detail',['id' => $id]);
エディタのformat設定はしていなく、手打ちでフォーマットしていたので設定してみます。

2020-11-30 13:06 UTC, cawauchi6204 commented on backend/app/Http/Controllers/CommentsController.php
> +    $comment->posts_id = $posts_id;
```php
$posts_id = $request->posts_id;
$comment->posts_id = $posts_id;
```

posts_idの複数系もgrepで直し残し探してみます。

確かにposts_id = $request->posts_idの一文は全くいらないですね

2020-12-08 04:39 UTC, wazyu-17 approved these changes
問題なしです！レビュー通過です！

2020-12-08 12:15 UTC, merged